### ISSUE TITLE
Decide infrastructure stack

### ISSUE THREAD

**Issue by clee231** [acm-uic/IaC#3]
This issue is to mostly discuss the infrastructure stack to provision any changes within the network.

Please post your suggestions here.

I'll post my proposed stack later...

**Comment by jgensler8** [comment]
Back when I was part of the Linux Users Group, I spent [some](http://lug.cs.uic.edu/wiki/doku.php?id=cloud) [time](https://github.com/lugatuic/lug-docs/commit/d38fe8e6f977709ffb9661da822d99a8cd611147) thinking about how to build a Platform as a Service for developers at UIC. I am not sure I have as much context as both of you, but I can try and provide some guidance from my experience after graduation.

I would strongly advise to keep things simple. As you are only at school for a limited amount of time, you'll want to pick technologies that will be maintainable in the long term. If the project is more of a learning experience, then the choices you make might not matter quite as much.

I think a good place to start is list the existing tech stack. Adding constraints to a decision making process is an easier way to get to an conclusion. From my experience, you'll want to have a good foundation on core or shared services. Usually, these are things like Identity Providers (Active Directory/LDAP) and DNS (Not sure what ACM uses). Those systems are unlikely to change in the long term so understand their limitations. Identity will usually be at the core of your PaaS so make sure you Identity Provider includes some sort of role management (acm members vs non members, admins vs users).

Given that this repository will focus on defining what the infrastructure is, you'll probably want to decide on who or what orchestrates any sort of rollout. Are changes rolled out by CI pipeline? Is is run from a administrator's laptop? Keep in mind, there might not be one answer for all services. From my experience, CI pipelines are preferred because you can audit who is making changes. Usually, all team members can receive emails when PRs are open or merged so there is a considerable amount of visibility that can be gained through central management of your infrastructure. This sort of automation can lead to even more interesting workflows like ChatOps. I think [Etsy](https://codeascraft.com/2018/10/10/etsys-experiment-with-immutable-documentation/) and [GitHub](https://speakerdeck.com/jnewland/chatops-at-github?slide=35) are two larger organizations that have put considerable engineering hours into their engineering workflows and use chat as a way to communicate knowledge and automate processes.

Our team has tried out Matchbox before though we never went forward with it (story for another time). I _think_ that AWS uses Xen Hypervisor for its EC2 service ([based on this talk](https://youtu.be/agQMFIWr2h4?t=877)). I am not sure how hard maintaining Xen is or if many companies run it, but it might prove to be a good option for providing some VM abstraction on top of your hardware. There appears to be [some open source work](https://github.com/terra-farm/terraform-provider-xenserver) done with Terraform to create VMs so that might be sufficient for your use case. If you have questions about Terraform, Go, or writing a terraform provider, I have some experience and can provide some guidance.

After you have built a hardware abstraction, then you can get into the Configuration Management and Orchestration tools that you have listed above. I think you may have left out [cloud-init](https://cloudinit.readthedocs.io/en/latest/) which is used [by EC2](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/amazon-linux-ami-basics.html#amazon-linux-cloud-init) and [Ubuntu](https://blog.ubuntu.com/2014/12/11/snappy-ubuntu-core-and-cloud-init). In terms of schedulers, I think Kubernetes has made a big wave over the last few years and has plenty of projects for all types of development. As almost all cloud providers have some sort of managed Kubernetes service, I think that learning how to use Kubernetes is a great skill to learn before graduating (for you and for future students). I think you can use [dex](https://github.com/dexidp/dex) with Active Directory to act as an OIDC provider for Kubernetes.

In terms of monitoring, I would recommend Prometheus. As you have brought up the SRE Book, check out the [Introduction on Monitoring](https://landing.google.com/sre/sre-book/chapters/monitoring-distributed-systems/) and the [detailed chapter on Practical Alerting](https://landing.google.com/sre/sre-book/chapters/practical-alerting/). In particular, take a look at the "Sharding the Monitoring Topology" section. Building complex reporting and alerting queries is only possible with a language that lets you easily express that complexity.

If needed, I may be able to visit UIC and clarify some of these point or provide some mentoring. Hopefully, this information is helpful!

**Comment by bmiddha** [comment]
Thank you Jeff!
I am glad you reached out.

We want to move everything we can to containers on Kubernetes making our server less monolithic and our services more reliable.

**Comment by timchoh585** [comment]
If it helps, and you're still trying to learn kubernetes, if Professor
Grechanik is still there's he is a very valuable resource. His class on
cloud computing has a project on it as well as he enjoys talking to people
about it. If you plan on using k8s, I would recommend talking with him
about it.

**Comment by ezalenski** [comment]
Kubernetes 10/10 would kubes again
